### ISSUE TITLE
Consider how to manage HTTP checks for CircleCI Server instances

### ISSUE THREAD

**Issue by kelvintaywl** [kelvintaywl-cci/circleci-container-runner-help#2]
Right now, the support-bundle manifest will try to ping the CircleCI Runner API:

This is currently hardcoded to runner.circleci.com (valid for Cloud customers).
For CircleCI Server instances, the domain should be their server's domain instead.

I understand there is no way to make this manifest "dynamic" (e.g., set that url value based on env var).
Maybe we need additional steps like using `sed` and/or `yq` to modify the yaml before running the `kubectl support-bundle ...` command.

**Comment by imlogang** [comment]
@kelvintaywl Love this idea btw! 

Instead of doing the following since we will need to eventually have a dynamic `RUNNER_API` URL:
https://github.com/kelvintaywl-cci/circleci-container-runner-help/blob/main/support-bundle.yaml#L20-L29

We do something like the following?
```
    - exec:
        name: runner_api
        selector:
          - app=container-agent
        command: 
          - /bin/sh 
          - -c 
          - "RUNNER_API_HOST=$(echo $RUNNER_API | cut -d'/' -f3); wget $RUNNER_API_HOST/api/v2/runner?namespace=foobar"
        timeout: 10s
```

I've confirmed this works locally, and gives the expected `401 Unauthorized` 
```
Connecting to runner.circleci.com (18.154.242.21:80)
Connecting to runner.circleci.com (18.154.242.87:443)
wget: server returned error: HTTP/1.1 401 Unauthorized
```
and works even in a server environment
```
Connecting to cciserver.logangodsey.com (192.168.30.200:80)
wget: server returned error: HTTP/1.1 401 Unauthorized
```

Not sure I enjoy the IP print out though 🤔
